
//=======================================================
//  This code is generated by Terasic System Builder
//=======================================================

module TFLipFlop(

	//////////// CLOCK //////////
	input 		          		CLOCK_50,
	input 		          		CLOCK2_50,
	input 		          		CLOCK3_50,
	inout 		          		CLOCK4_50,

	//////////// KEY //////////
	input 		     [3:0]		KEY,
	input 		          		RESET_N,

	//////////// LED //////////
	output		     [9:0]		LEDR,

	//////////// SW //////////
	input 		     [9:0]		SW
);

//=======================================================
//  REG/WIRE declarations
//=======================================================

	wire CLK;
//=======================================================
//  Structural coding
//=======================================================
	
	assign CLK = ~KEY[0];
	assign LEDR[9] = CLK;
	ToggleFF(SW[0], CLK, SW[1], LEDR[0]);

endmodule
