
//=======================================================
//  This code is generated by Terasic System Builder
//=======================================================

module SRLatch(

	//////////// LED //////////
	output		     [9:0]		LEDR,

	//////////// SW //////////
	input 		     [9:0]		SW
);

//=======================================================
//  REG/WIRE declarations
//=======================================================

	wire Q1, Qbar1, Q2, Qbar2;

//=======================================================
//  Structural coding
//=======================================================
	assign S1 = SW[3];
	assign R1 = SW[2];
	assign S2 = SW[1];
	assign R2 = SW[0];
	sr_latch_with_gates(S1, R1, Q1, Qbar1);
	sr_latch_with_dataflow(S2, R2, Q2, Qbar2);
	assign LEDR[3] = Q1;
	assign LEDR[2] = Qbar1;
	assign LEDR[1] = Q2;
	assign LEDR[0] = Qbar2;
endmodule
