
//=======================================================
//  This code is generated by Terasic System Builder
//=======================================================

module D_FlipFlop(

	//////////// CLOCK //////////
	input 		          		CLOCK_50,
	input 		          		CLOCK2_50,
	input 		          		CLOCK3_50,
	inout 		          		CLOCK4_50,

	//////////// LED //////////
	output		     [9:0]		LEDR,

	//////////// SW //////////
	input 		     [9:0]		SW
);



//=======================================================
//  REG/WIRE declarations
//=======================================================

wire D, Enable, Q, Qbar, QClk;
assign D = SW[0];
assign Enable = SW[1];
D_latch_behaviour(D, Enable, Q, Qbar);
D_ff_behavior(D, CLOCK_50, QClk);

//=======================================================
//  Structural coding
//=======================================================

assign LEDR[0] = Q;
assign LEDR[1] = Qbar;
assign LEDR[2] = QClk;

endmodule
