
//=======================================================
//  This code is generated by Terasic System Builder
//=======================================================

module Slide(

	//////////// KEY //////////
	input 		     [3:0]		KEY,
	input 		          		RESET_N,

	//////////// LED //////////
	output		     [9:0]		LEDR,

	//////////// microSD Card //////////
	output		          		SD_CLK,
	inout 		          		SD_CMD,
	inout 		     [3:0]		SD_DATA,

	//////////// GPIO_0, GPIO_0 connect to GPIO Default //////////
	inout 		    [35:0]		GPIO
);



//=======================================================
//  REG/WIRE declarations
//=======================================================
	assign LEDR[9] = ~GPIO[3:0];
	assign LEDR[8] = ~GPIO[7:4];
	assign LEDR[7] = ~GPIO[11:8];
	assign LEDR[6] = ~GPIO[15:12];
	assign LEDR[5] = ~GPIO[19:16];
	assign LEDR[4] = ~GPIO[23:20];
	assign LEDR[3] = ~GPIO[27:24];
	assign LEDR[2] = ~GPIO[31:28];
	assign LEDR[1] = ~GPIO[35:32];


//=======================================================
//  Structural coding
//=======================================================



endmodule
