
//=======================================================
//  This code is generated by Terasic System Builder
//=======================================================

module Slide(

	//////////// KEY //////////
	input 		     [3:0]		KEY,
	input 		          		RESET_N,

	//////////// LED //////////
	output		     [9:0]		LEDR,
	
	//////////// SEG7 //////////
	output		     [6:0]		HEX0,
	output		     [6:0]		HEX1,
	output		     [6:0]		HEX2,
	output		     [6:0]		HEX3,
	output		     [6:0]		HEX4,
	output		     [6:0]		HEX5,

	//////////// microSD Card //////////
	output		          		SD_CLK,
	inout 		          		SD_CMD,
	inout 		     [3:0]		SD_DATA,

	//////////// GPIO_0, GPIO_0 connect to GPIO Default //////////
	inout 		    [35:0]		GPIO
);



//=======================================================
//  REG/WIRE declarations
//=======================================================
	assign LEDR[9] = ~GPIO[3 : 0];
	assign LEDR[8] = ~GPIO[6 : 4];
	assign LEDR[7] = ~GPIO[10: 7];
	assign LEDR[6] = ~GPIO[14:11];
	assign LEDR[5] = ~GPIO[17:15];
	assign LEDR[4] = ~GPIO[21:18];
	assign LEDR[3] = ~GPIO[24:22];
	assign LEDR[2] = ~GPIO[28:25];
	assign LEDR[1] = ~GPIO[32:29];
	assign LEDR[0] = ~GPIO[35:33];
	
	assign HEX5[0]   = GPIO[3 : 0];
	assign HEX4[0]   = GPIO[6 : 4];
	assign HEX3[0]   = GPIO[10: 7];
	assign HEX2[0]   = GPIO[14:11];
	assign HEX1[0]   = GPIO[17:15];
	assign HEX0[0]   = GPIO[20:18];
	assign HEX0[2:1] = GPIO[23:21];
	assign HEX1[3]   = GPIO[26:24];
	assign HEX2[3]   = GPIO[28:27];
	assign HEX3[3]   = GPIO[31:29];
	assign HEX4[3]   = GPIO[31:30];
	assign HEX5[3]   = GPIO[33:32];
	assign HEX5[5:4] = GPIO[35:34];

endmodule
