
//=======================================================
//  This code is generated by Terasic System Builder
//=======================================================

module Slide(

	//////////// KEY //////////
	input 		     [3:0]		KEY,
	input 		          		RESET_N,

	//////////// LED //////////
	output		     [9:0]		LEDR,
	
	//////////// SEG7 //////////
	output		     [6:0]		HEX0,
	output		     [6:0]		HEX1,
	output		     [6:0]		HEX2,
	output		     [6:0]		HEX3,
	output		     [6:0]		HEX4,
	output		     [6:0]		HEX5,

	//////////// microSD Card //////////
	output		          		SD_CLK,
	inout 		          		SD_CMD,
	inout 		     [3:0]		SD_DATA,

	//////////// GPIO_0, GPIO_0 connect to GPIO Default //////////
	inout 		    [35:0]		GPIO
);



//=======================================================
//  REG/WIRE declarations
//=======================================================

	wire a, b, c, d, e, f, g, h, i, j;
	wire k, l, m, n, o, p, q, r;
	assign a = ~GPIO[3 : 0];
	assign b = ~GPIO[6 : 4];
	assign c = ~GPIO[10: 7];
	assign d = ~GPIO[14:11];
	assign e = ~GPIO[17:15];
	assign f = ~GPIO[21:18];
	assign g = ~GPIO[24:22];
	assign h = ~GPIO[28:25];
	assign i = ~GPIO[32:29];
	assign j = ~GPIO[35:33];
	assign k = GPIO[20:18];
	assign l = GPIO[23:21];
	assign m = GPIO[26:24];
	assign n = GPIO[28:27];
	assign o = GPIO[31:29];
	assign p = GPIO[31:30];
	assign q = GPIO[33] || GPIO[32];
	assign r = GPIO[35] || GPIO[34];
	
	
	assign LEDR[9] = a;
	assign LEDR[8] = b;
	assign LEDR[7] = c;
	assign LEDR[6] = d;
	assign LEDR[5] = e;
	assign LEDR[4] = f;
	assign LEDR[3] = g;
	assign LEDR[2] = h;
	assign LEDR[1] = i;
	assign LEDR[0] = j;
	
	assign HEX5[0] = ~a;
	assign HEX4[0] = ~b;
	assign HEX3[0] = ~c;
	assign HEX2[0] = ~d;
	assign HEX1[0] = ~e;
	assign HEX0[0] = k;
	assign HEX0[1] = l;
	assign HEX0[2] = l;
	assign HEX1[3] = m;
	assign HEX2[3] = n;
	assign HEX3[3] = o;
	assign HEX4[3] = p;
	assign HEX5[3] = q;
	assign HEX5[4] = r;
	assign HEX5[5] = r;

endmodule
